version: '3'
services:
  test-dependency:
    build: ./test-dependency
    expose:
      - "80"
  hystrix-server:
    build: ./hystrix-server
    expose:
      - "8080"
    ports:
      - "8080:8080"
    links:
      - "test-dependency:testserver"
  turbine:
    build: ./turbine
    expose:
      - "80"
    environment:
      - "TURBINE_STREAMS=http://hystrix-server:8080/api/hystrix.stream"
    links:
      - "hystrix-server"
  hystrix-dashboard:
    build: ./dashboard
    ports:
      - "8000:8080"
    links:
      - "turbine"
      - "hystrix-server"

